export MANPATH=$HOME/.linuxbrew/share/man:$MANPATH
export INFOPATH=$HOME/.linuxbrew/share/info:$INFOPATH
export PATH=$HOME/.yarn/bin:$HOME/.luarocks/bin:$HOME/go/bin:$HOME/.cargo/bin:$HOME/.config/composer/vendor/bin:/usr/local/bin:/usr/local/sbin:/usr/local/opt/coreutils/libexec/gnubin:$HOME/.linuxbrew/bin:$PATH
export MANPATH=/usr/local/opt/coreutils/libexec/gnubin:$MANPATH
# export TERM="xterm-256color"
# export TERM="rxvt-256color"
export LANG=zh_CN.UTF-8
export ZLS_COLORS=${LS_COLORS}
# export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python2
# export WORKON_HOME=~/.virtualenvs
export GOPATH=~/go
export RUST_SRC_PATH=~/rust/rust/src
#export GOPATH=~/go:~/cloud/rcloud/goClient
